### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Nic30** [mutalabs/virtualhdl#1]
Hello,
is this project dead?
If it is can you please remove it?

There is a [issue](https://github.com/SymbiFlow/ideas/issues/19) about some "FPGA assembly language" it seems to me that we will have to implement some library because FIRRTL library which we would like to use at first is probably tied with Scala and Chisel3.

I would like (potentially) to use name very similar to this one and users would probably find this repo first.

**Comment by euripedesrocha** [comment]
I will not assume that it's dead(it's kind of stopped without a schedule) but why do you want me to remove the repository? I see no reason to do it. Create your project work on it and if you find that the existence of this one is a problem for you I rename, delete or whatever...

**Comment by Nic30** [comment]
Ok, I was thinking that this repo is only relict. I am sorry if it sounded like something else.

**Comment by euripedesrocha** [comment]
No problem. As said if we face any concret problem because of this particular repository we handle it.
